name: Check

# on: [push]
on:
  push:
    branches:
      - master
      - develop

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .


    steps:
    - name: SayHello
      run: echo "hello world!!"

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build test
      run: cargo build --release --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Lint with clippy
      run: cargo clippy --all-targets --all-features

    - name: Check formatting
      run: cargo fmt --all --check

